### ISSUE TITLE
Jsoncpp crashes when invalid wallet is given

### ISSUE THREAD

**Issue by matejm** [electronpass/libelectronpass#1]
When trying to decrypt and load wallet object sometimes crash occures inside of this function.

    electronpass::Wallet load(const std::string &data, const Crypto &crypto, int &error);

Error stack trace:
    
    terminate called after throwing an instance of 'Json::LogicError'
      what():  in Json::Value::resolveReference(key, end): requires objectValue
    Aborted (core dumped)

Crash does not happen on any invalid json string, just on few of them. Simplest example to crash the program is

    ""

For most invalid json strings function already returns correct error code (`2` - invalid json object) without crash.

**Comment by DzinVision** [comment]
Invalid JSON test does not crash. I tested multiple invalid JSON strings and could not find one that crashes the tests.

**Comment by matejm** [comment]
For most of invalid json string it doesn't, but for some of them it does. Few examples:

    ""
    "something"
    ":"randomText"}

**Comment by DzinVision** [comment]
All of the above has been fixed in e434291.
